// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class Kierowcy
{
    public int IdKierowcy { get; set; }

    public string Imię { get; set; }

    public string Nazwisko { get; set; }

    public string Adres { get; set; }

    public string NrTelefonu { get; set; }
}