// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class KierowcaSamochod
{
    public int? IdKierowcy { get; set; }

    public int? IdSamochodu { get; set; }

    public virtual Kierowcy IdKierowcyNavigation { get; set; }

    public virtual Samochody IdSamochoduNavigation { get; set; }
}