// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class Ladunek
{
    public int IdLadunek { get; set; }

    public int? IdSamochod { get; set; }

    public string Status { get; set; }

    public virtual Samochody IdSamochodNavigation { get; set; }

}