// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class OdjazdyOkolica
{
    public string IdRejon { get; set; }

    public int? NrDoku { get; set; }

    public DateTime? CzasOdjazdu { get; set; }

    public int? IdLadunek { get; set; }

    public virtual Ladunek IdLadunekNavigation { get; set; }

    public virtual Rejon IdRejonNavigation { get; set; }

    public virtual Doki NrDokuNavigation { get; set; }
}