// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class Paczki
{
    public int IdPaczki { get; set; }

    public bool? Gabaryt { get; set; }

    public string KodPocztowyNadawcy { get; set; }

    public string KodPocztowyOdbiorcy { get; set; }

    public string DaneOdbiorcy { get; set; }

    public string DaneNadawcy { get; set; }

    public string AdresNadawcy { get; set; }

    public string AdresOdbiorcy { get; set; }

    public DateTime? DataNadania { get; set; }

    /// <summary>
    /// Gdzie się teraz znajduje
    /// </summary>
    public string Status { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public bool? CzyZniszczona { get; set; }
}