// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class Region
{
    public string IdRegion { get; set; }

    public string NazwaMagazynu { get; set; }
}