// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class Rejon
{
    public string IdRejon { get; set; }

    public string KodPocztowy { get; set; }
}