// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class Samochody
{
    public int SamochodId { get; set; }

    public string Rejestracja { get; set; }

    public string Typ { get; set; }

    public virtual ICollection<Ladunek> Laduneks { get; set; } = new List<Ladunek>();
}