// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapp.api.Models;

public partial class Uprawnienium
{
    public int IdUprawnienia { get; set; }

    public string NazwaUprawnienia { get; set; }

    public virtual ICollection<Pracownicy> Pracownicies { get; set; } = new List<Pracownicy>();
}